directories:
  # Define the directory structure for the project
  input: []                # Directory for input files
  output:                  # Directory for output files
    - plots                # Subdirectory for plots
    - tables               # Subdirectory for tables
  logs: []                 # Directory for logs
  temp: []                 # Temporary working directory

backup:
  default_archive_name: "project_backup"  # Default name for backup archives

filename:
  default_prefix: "datafile"             # Default prefix for generated filenames
  default_extension: "csv"              # Default file extension for generated filenames

validation:
  check_missing_values: true
  check_duplicate_columns: true
  check_outliers: true         # Enable or disable outlier detection
  missing_value_threshold: 0.2 # Allow up to 20% missing values
